# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password:
  host: db:3306

development:
  <<: *default
  database: development.mysql

test:
  <<: *default
  database: test.mysql

production:
  <<: *default
  database: production.mysql
